/**
 * Country and nationality reference data.
 * Single source of truth for country dropdowns, dial codes, and nationality lists.
 */
export interface Country {
  name: string;
  code: string; // ISO-2
  dial: string;
  nationality: string;
}

// Curated full list (ISO-3166-1).
export const COUNTRIES: Country[] = [
  { name: 'Afghanistan', code: 'AF', dial: '+93', nationality: 'Afghan' },
  { name: 'Albania', code: 'AL', dial: '+355', nationality: 'Albanian' },
  { name: 'Algeria', code: 'DZ', dial: '+213', nationality: 'Algerian' },
  { name: 'Andorra', code: 'AD', dial: '+376', nationality: 'Andorran' },
  { name: 'Angola', code: 'AO', dial: '+244', nationality: 'Angolan' },
  { name: 'Argentina', code: 'AR', dial: '+54', nationality: 'Argentine' },
  { name: 'Armenia', code: 'AM', dial: '+374', nationality: 'Armenian' },
  { name: 'Australia', code: 'AU', dial: '+61', nationality: 'Australian' },
  { name: 'Austria', code: 'AT', dial: '+43', nationality: 'Austrian' },
  { name: 'Azerbaijan', code: 'AZ', dial: '+994', nationality: 'Azerbaijani' },
  { name: 'Bahamas', code: 'BS', dial: '+1', nationality: 'Bahamian' },
  { name: 'Bahrain', code: 'BH', dial: '+973', nationality: 'Bahraini' },
  { name: 'Bangladesh', code: 'BD', dial: '+880', nationality: 'Bangladeshi' },
  { name: 'Barbados', code: 'BB', dial: '+1', nationality: 'Barbadian' },
  { name: 'Belarus', code: 'BY', dial: '+375', nationality: 'Belarusian' },
  { name: 'Belgium', code: 'BE', dial: '+32', nationality: 'Belgian' },
  { name: 'Belize', code: 'BZ', dial: '+501', nationality: 'Belizean' },
  { name: 'Benin', code: 'BJ', dial: '+229', nationality: 'Beninese' },
  { name: 'Bhutan', code: 'BT', dial: '+975', nationality: 'Bhutanese' },
  { name: 'Bolivia', code: 'BO', dial: '+591', nationality: 'Bolivian' },
  { name: 'Bosnia and Herzegovina', code: 'BA', dial: '+387', nationality: 'Bosnian' },
  { name: 'Botswana', code: 'BW', dial: '+267', nationality: 'Botswanan' },
  { name: 'Brazil', code: 'BR', dial: '+55', nationality: 'Brazilian' },
  { name: 'Brunei', code: 'BN', dial: '+673', nationality: 'Bruneian' },
  { name: 'Bulgaria', code: 'BG', dial: '+359', nationality: 'Bulgarian' },
  { name: 'Burkina Faso', code: 'BF', dial: '+226', nationality: 'Burkinabe' },
  { name: 'Burundi', code: 'BI', dial: '+257', nationality: 'Burundian' },
  { name: 'Cambodia', code: 'KH', dial: '+855', nationality: 'Cambodian' },
  { name: 'Cameroon', code: 'CM', dial: '+237', nationality: 'Cameroonian' },
  { name: 'Canada', code: 'CA', dial: '+1', nationality: 'Canadian' },
  { name: 'Cape Verde', code: 'CV', dial: '+238', nationality: 'Cape Verdean' },
  { name: 'Central African Republic', code: 'CF', dial: '+236', nationality: 'Central African' },
  { name: 'Chad', code: 'TD', dial: '+235', nationality: 'Chadian' },
  { name: 'Chile', code: 'CL', dial: '+56', nationality: 'Chilean' },
  { name: 'China', code: 'CN', dial: '+86', nationality: 'Chinese' },
  { name: 'Colombia', code: 'CO', dial: '+57', nationality: 'Colombian' },
  { name: 'Comoros', code: 'KM', dial: '+269', nationality: 'Comorian' },
  { name: 'Congo', code: 'CG', dial: '+242', nationality: 'Congolese' },
  { name: 'Costa Rica', code: 'CR', dial: '+506', nationality: 'Costa Rican' },
  { name: 'Croatia', code: 'HR', dial: '+385', nationality: 'Croatian' },
  { name: 'Cuba', code: 'CU', dial: '+53', nationality: 'Cuban' },
  { name: 'Cyprus', code: 'CY', dial: '+357', nationality: 'Cypriot' },
  { name: 'Czech Republic', code: 'CZ', dial: '+420', nationality: 'Czech' },
  { name: 'Denmark', code: 'DK', dial: '+45', nationality: 'Danish' },
  { name: 'Djibouti', code: 'DJ', dial: '+253', nationality: 'Djiboutian' },
  { name: 'Dominican Republic', code: 'DO', dial: '+1', nationality: 'Dominican' },
  { name: 'Ecuador', code: 'EC', dial: '+593', nationality: 'Ecuadorian' },
  { name: 'Egypt', code: 'EG', dial: '+20', nationality: 'Egyptian' },
  { name: 'El Salvador', code: 'SV', dial: '+503', nationality: 'Salvadoran' },
  { name: 'Estonia', code: 'EE', dial: '+372', nationality: 'Estonian' },
  { name: 'Ethiopia', code: 'ET', dial: '+251', nationality: 'Ethiopian' },
  { name: 'Fiji', code: 'FJ', dial: '+679', nationality: 'Fijian' },
  { name: 'Finland', code: 'FI', dial: '+358', nationality: 'Finnish' },
  { name: 'France', code: 'FR', dial: '+33', nationality: 'French' },
  { name: 'Gabon', code: 'GA', dial: '+241', nationality: 'Gabonese' },
  { name: 'Gambia', code: 'GM', dial: '+220', nationality: 'Gambian' },
  { name: 'Georgia', code: 'GE', dial: '+995', nationality: 'Georgian' },
  { name: 'Germany', code: 'DE', dial: '+49', nationality: 'German' },
  { name: 'Ghana', code: 'GH', dial: '+233', nationality: 'Ghanaian' },
  { name: 'Greece', code: 'GR', dial: '+30', nationality: 'Greek' },
  { name: 'Guatemala', code: 'GT', dial: '+502', nationality: 'Guatemalan' },
  { name: 'Guinea', code: 'GN', dial: '+224', nationality: 'Guinean' },
  { name: 'Guyana', code: 'GY', dial: '+592', nationality: 'Guyanese' },
  { name: 'Haiti', code: 'HT', dial: '+509', nationality: 'Haitian' },
  { name: 'Honduras', code: 'HN', dial: '+504', nationality: 'Honduran' },
  { name: 'Hong Kong', code: 'HK', dial: '+852', nationality: 'Hong Konger' },
  { name: 'Hungary', code: 'HU', dial: '+36', nationality: 'Hungarian' },
  { name: 'Iceland', code: 'IS', dial: '+354', nationality: 'Icelander' },
  { name: 'India', code: 'IN', dial: '+91', nationality: 'Indian' },
  { name: 'Indonesia', code: 'ID', dial: '+62', nationality: 'Indonesian' },
  { name: 'Iran', code: 'IR', dial: '+98', nationality: 'Iranian' },
  { name: 'Iraq', code: 'IQ', dial: '+964', nationality: 'Iraqi' },
  { name: 'Ireland', code: 'IE', dial: '+353', nationality: 'Irish' },
  { name: 'Israel', code: 'IL', dial: '+972', nationality: 'Israeli' },
  { name: 'Italy', code: 'IT', dial: '+39', nationality: 'Italian' },
  { name: 'Jamaica', code: 'JM', dial: '+1', nationality: 'Jamaican' },
  { name: 'Japan', code: 'JP', dial: '+81', nationality: 'Japanese' },
  { name: 'Jordan', code: 'JO', dial: '+962', nationality: 'Jordanian' },
  { name: 'Kazakhstan', code: 'KZ', dial: '+7', nationality: 'Kazakh' },
  { name: 'Kenya', code: 'KE', dial: '+254', nationality: 'Kenyan' },
  { name: 'Kuwait', code: 'KW', dial: '+965', nationality: 'Kuwaiti' },
  { name: 'Kyrgyzstan', code: 'KG', dial: '+996', nationality: 'Kyrgyzstani' },
  { name: 'Laos', code: 'LA', dial: '+856', nationality: 'Laotian' },
  { name: 'Latvia', code: 'LV', dial: '+371', nationality: 'Latvian' },
  { name: 'Lebanon', code: 'LB', dial: '+961', nationality: 'Lebanese' },
  { name: 'Liberia', code: 'LR', dial: '+231', nationality: 'Liberian' },
  { name: 'Libya', code: 'LY', dial: '+218', nationality: 'Libyan' },
  { name: 'Lithuania', code: 'LT', dial: '+370', nationality: 'Lithuanian' },
  { name: 'Luxembourg', code: 'LU', dial: '+352', nationality: 'Luxembourger' },
  { name: 'Macau', code: 'MO', dial: '+853', nationality: 'Macanese' },
  { name: 'Madagascar', code: 'MG', dial: '+261', nationality: 'Malagasy' },
  { name: 'Malawi', code: 'MW', dial: '+265', nationality: 'Malawian' },
  { name: 'Malaysia', code: 'MY', dial: '+60', nationality: 'Malaysian' },
  { name: 'Maldives', code: 'MV', dial: '+960', nationality: 'Maldivian' },
  { name: 'Mali', code: 'ML', dial: '+223', nationality: 'Malian' },
  { name: 'Malta', code: 'MT', dial: '+356', nationality: 'Maltese' },
  { name: 'Mauritania', code: 'MR', dial: '+222', nationality: 'Mauritanian' },
  { name: 'Mauritius', code: 'MU', dial: '+230', nationality: 'Mauritian' },
  { name: 'Mexico', code: 'MX', dial: '+52', nationality: 'Mexican' },
  { name: 'Moldova', code: 'MD', dial: '+373', nationality: 'Moldovan' },
  { name: 'Monaco', code: 'MC', dial: '+377', nationality: 'Monacan' },
  { name: 'Mongolia', code: 'MN', dial: '+976', nationality: 'Mongolian' },
  { name: 'Montenegro', code: 'ME', dial: '+382', nationality: 'Montenegrin' },
  { name: 'Morocco', code: 'MA', dial: '+212', nationality: 'Moroccan' },
  { name: 'Mozambique', code: 'MZ', dial: '+258', nationality: 'Mozambican' },
  { name: 'Myanmar', code: 'MM', dial: '+95', nationality: 'Burmese' },
  { name: 'Namibia', code: 'NA', dial: '+264', nationality: 'Namibian' },
  { name: 'Nepal', code: 'NP', dial: '+977', nationality: 'Nepali' },
  { name: 'Netherlands', code: 'NL', dial: '+31', nationality: 'Dutch' },
  { name: 'New Zealand', code: 'NZ', dial: '+64', nationality: 'New Zealander' },
  { name: 'Nicaragua', code: 'NI', dial: '+505', nationality: 'Nicaraguan' },
  { name: 'Niger', code: 'NE', dial: '+227', nationality: 'Nigerien' },
  { name: 'Nigeria', code: 'NG', dial: '+234', nationality: 'Nigerian' },
  { name: 'North Korea', code: 'KP', dial: '+850', nationality: 'North Korean' },
  { name: 'North Macedonia', code: 'MK', dial: '+389', nationality: 'Macedonian' },
  { name: 'Norway', code: 'NO', dial: '+47', nationality: 'Norwegian' },
  { name: 'Oman', code: 'OM', dial: '+968', nationality: 'Omani' },
  { name: 'Pakistan', code: 'PK', dial: '+92', nationality: 'Pakistani' },
  { name: 'Palestine', code: 'PS', dial: '+970', nationality: 'Palestinian' },
  { name: 'Panama', code: 'PA', dial: '+507', nationality: 'Panamanian' },
  { name: 'Papua New Guinea', code: 'PG', dial: '+675', nationality: 'Papua New Guinean' },
  { name: 'Paraguay', code: 'PY', dial: '+595', nationality: 'Paraguayan' },
  { name: 'Peru', code: 'PE', dial: '+51', nationality: 'Peruvian' },
  { name: 'Philippines', code: 'PH', dial: '+63', nationality: 'Filipino' },
  { name: 'Poland', code: 'PL', dial: '+48', nationality: 'Polish' },
  { name: 'Portugal', code: 'PT', dial: '+351', nationality: 'Portuguese' },
  { name: 'Qatar', code: 'QA', dial: '+974', nationality: 'Qatari' },
  { name: 'Romania', code: 'RO', dial: '+40', nationality: 'Romanian' },
  { name: 'Russia', code: 'RU', dial: '+7', nationality: 'Russian' },
  { name: 'Rwanda', code: 'RW', dial: '+250', nationality: 'Rwandan' },
  { name: 'Saudi Arabia', code: 'SA', dial: '+966', nationality: 'Saudi' },
  { name: 'Senegal', code: 'SN', dial: '+221', nationality: 'Senegalese' },
  { name: 'Serbia', code: 'RS', dial: '+381', nationality: 'Serbian' },
  { name: 'Singapore', code: 'SG', dial: '+65', nationality: 'Singaporean' },
  { name: 'Slovakia', code: 'SK', dial: '+421', nationality: 'Slovak' },
  { name: 'Slovenia', code: 'SI', dial: '+386', nationality: 'Slovenian' },
  { name: 'Somalia', code: 'SO', dial: '+252', nationality: 'Somali' },
  { name: 'South Africa', code: 'ZA', dial: '+27', nationality: 'South African' },
  { name: 'South Korea', code: 'KR', dial: '+82', nationality: 'South Korean' },
  { name: 'Spain', code: 'ES', dial: '+34', nationality: 'Spanish' },
  { name: 'Sri Lanka', code: 'LK', dial: '+94', nationality: 'Sri Lankan' },
  { name: 'Sudan', code: 'SD', dial: '+249', nationality: 'Sudanese' },
  { name: 'Sweden', code: 'SE', dial: '+46', nationality: 'Swedish' },
  { name: 'Switzerland', code: 'CH', dial: '+41', nationality: 'Swiss' },
  { name: 'Syria', code: 'SY', dial: '+963', nationality: 'Syrian' },
  { name: 'Taiwan', code: 'TW', dial: '+886', nationality: 'Taiwanese' },
  { name: 'Tajikistan', code: 'TJ', dial: '+992', nationality: 'Tajik' },
  { name: 'Tanzania', code: 'TZ', dial: '+255', nationality: 'Tanzanian' },
  { name: 'Thailand', code: 'TH', dial: '+66', nationality: 'Thai' },
  { name: 'Togo', code: 'TG', dial: '+228', nationality: 'Togolese' },
  { name: 'Trinidad and Tobago', code: 'TT', dial: '+1', nationality: 'Trinidadian' },
  { name: 'Tunisia', code: 'TN', dial: '+216', nationality: 'Tunisian' },
  { name: 'Turkey', code: 'TR', dial: '+90', nationality: 'Turkish' },
  { name: 'Turkmenistan', code: 'TM', dial: '+993', nationality: 'Turkmen' },
  { name: 'Uganda', code: 'UG', dial: '+256', nationality: 'Ugandan' },
  { name: 'Ukraine', code: 'UA', dial: '+380', nationality: 'Ukrainian' },
  { name: 'United Arab Emirates', code: 'AE', dial: '+971', nationality: 'Emirati' },
  { name: 'United Kingdom', code: 'GB', dial: '+44', nationality: 'British' },
  { name: 'United States', code: 'US', dial: '+1', nationality: 'American' },
  { name: 'Uruguay', code: 'UY', dial: '+598', nationality: 'Uruguayan' },
  { name: 'Uzbekistan', code: 'UZ', dial: '+998', nationality: 'Uzbek' },
  { name: 'Venezuela', code: 'VE', dial: '+58', nationality: 'Venezuelan' },
  { name: 'Vietnam', code: 'VN', dial: '+84', nationality: 'Vietnamese' },
  { name: 'Yemen', code: 'YE', dial: '+967', nationality: 'Yemeni' },
  { name: 'Zambia', code: 'ZM', dial: '+260', nationality: 'Zambian' },
  { name: 'Zimbabwe', code: 'ZW', dial: '+263', nationality: 'Zimbabwean' },
];

export const COUNTRY_NAMES = COUNTRIES.map((c) => c.name);
export const NATIONALITIES = Array.from(new Set(COUNTRIES.map((c) => c.nationality))).sort();

export function findCountry(name: string): Country | undefined {
  return COUNTRIES.find((c) => c.name.toLowerCase() === name.toLowerCase());
}
